// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DoSumClient is the client API for DoSum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoSumClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type doSumClient struct {
	cc grpc.ClientConnInterface
}

func NewDoSumClient(cc grpc.ClientConnInterface) DoSumClient {
	return &doSumClient{cc}
}

func (c *doSumClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.DoSum/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoSumServer is the server API for DoSum service.
// All implementations must embed UnimplementedDoSumServer
// for forward compatibility
type DoSumServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	mustEmbedUnimplementedDoSumServer()
}

// UnimplementedDoSumServer must be embedded to have forward compatible implementations.
type UnimplementedDoSumServer struct {
}

func (UnimplementedDoSumServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedDoSumServer) mustEmbedUnimplementedDoSumServer() {}

// UnsafeDoSumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoSumServer will
// result in compilation errors.
type UnsafeDoSumServer interface {
	mustEmbedUnimplementedDoSumServer()
}

func RegisterDoSumServer(s grpc.ServiceRegistrar, srv DoSumServer) {
	s.RegisterService(&DoSum_ServiceDesc, srv)
}

func _DoSum_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoSumServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.DoSum/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoSumServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoSum_ServiceDesc is the grpc.ServiceDesc for DoSum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoSum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.DoSum",
	HandlerType: (*DoSumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _DoSum_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculatorpb/calculator.proto",
}
